jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8443
   servlet:
      context-path: /veterinaria
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/veterinaria_bd?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTime
      username: root
      password: admin
      spring.jpa.hibernate.ddl-auto: update
      spring.flyway.baselineOnMigrate: true
      hikari:
         poolName: pool
